# Site settings
# in the templates available like {{ site.myvariable }}.
title: 大美上行而兴
email: your-email@domain.com
brand: Your Name
headline: Inventor, Engineer and Futurist
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 畅远网络

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: your.name@gmail.com
phone: +86-12345678900

# Tracking
googleAnalitycsID: UA-83933844-1

